AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'vendor/bundle/**/*'
    - 'vendor/bundle/**/.*'
    - '.bundle/**/*'
    - 'bin/lolcommits'
    - 'lolcommits.gemspec'

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

inherit_from: .rubocop_todo.yml
