name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rake rubocop
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake test
  features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up imagemagick
      uses: mfinelli/setup-imagemagick@v5
      with:
        cache: true
    - name: Set up ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
    - name: Set up mplayer
      run: sudo apt-get install -y mplayer
    - name: Configure git user name, email
      run: |
        git config --global user.name $NAME
        git config --global user.email $EMAIL
      env:
        NAME: "George Costanza"
        EMAIL: "george.costanza@vandelay.com"
    - name: Run cucumber features
      run: bundle exec rake features
