name: Cucumber

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up imagemagick
      uses: mfinelli/setup-imagemagick@v5
      with:
        cache: true
    - name: Set up ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
    - name: Run cucumber features
      run: bundle exec rake features
